import { NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabaseAdmin';
import { getApiHost, getPortalHost, formatPaynetDate } from '@/lib/paynet';
import { randomUUID, randomBytes } from 'crypto';

function validatePaynetEnvVars(): { isValid: boolean; missing: string[] } {
  const missing: string[] = [];
  
  // Required for all modes
  const requiredVars = [
    'PAYNET_ENV',
    'PAYNET_USERNAME',
    'PAYNET_PASSWORD',
    'PAYNET_MERCHANT_CODE',
    'PAYNET_SALE_AREA_CODE',
    'PAYNET_CALLBACK_URL',
  ];

  // Check required vars
  for (const varName of requiredVars) {
    if (!process.env[varName]) {
      missing.push(varName);
    }
  }

  const paynetEnv = process.env.PAYNET_ENV;

  // If in live mode, check live-specific vars
  if (paynetEnv === 'live') {
    if (!process.env.PAYNET_API_HOST_LIVE) {
      missing.push('PAYNET_API_HOST_LIVE');
    }
    if (!process.env.PAYNET_PORTAL_HOST_LIVE) {
      missing.push('PAYNET_PORTAL_HOST_LIVE');
    }
    if (!process.env.PAYNET_NOTIFY_SECRET_KEY_LIVE) {
      missing.push('PAYNET_NOTIFY_SECRET_KEY_LIVE');
    }
  } else {
    // Test mode (default)
    if (!process.env.PAYNET_API_HOST_TEST) {
      missing.push('PAYNET_API_HOST_TEST');
    }
    if (!process.env.PAYNET_PORTAL_HOST_TEST) {
      missing.push('PAYNET_PORTAL_HOST_TEST');
    }
    if (!process.env.PAYNET_NOTIFY_SECRET_KEY_TEST) {
      missing.push('PAYNET_NOTIFY_SECRET_KEY_TEST');
    }
  }

  return {
    isValid: missing.length === 0,
    missing,
  };
}

export async function POST(req: Request) {
  // Version guard to confirm new code is deployed
  console.log('PAYNET_CREATE_HANDLER_VERSION', 'attempts-v2');

  try {
    // Validate environment variables first
    const validation = validatePaynetEnvVars();
    if (!validation.isValid) {
      console.error('Missing Paynet environment variables:', validation.missing.join(', '));
      return NextResponse.json(
        {
          error: 'PAYNET_CONFIG_MISSING',
          missing: validation.missing,
        },
        { status: 500 }
      );
    }

    // Parse and validate request body
    let body;
    try {
      body = await req.json();
    } catch (e) {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'Invalid JSON in request body',
        },
        { status: 400 }
      );
    }

    const { productId, amount, currency = 'MDL' } = body;

    // Body validation
    if (!productId || typeof productId !== 'string' || productId.trim() === '') {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'productId is required and must be a non-empty string',
        },
        { status: 400 }
      );
    }

    if (!amount || typeof amount !== 'number' || amount <= 0) {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'amount is required and must be a positive number',
        },
        { status: 400 }
      );
    }

    const customerFirstName =
      typeof body.customer_first_name === 'string' ? body.customer_first_name.trim() : '';
    const customerLastName =
      typeof body.customer_last_name === 'string' ? body.customer_last_name.trim() : '';
    const customerEmail =
      typeof body.customer_email === 'string' ? body.customer_email.trim().toLowerCase() : '';
    const customerPhoneRaw =
      typeof body.customer_phone === 'string' ? body.customer_phone.trim() : '';
    const customerPhoneDigits = customerPhoneRaw.replace(/\D/g, '');

    const emailOk = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(customerEmail);
    if (!customerFirstName || !customerLastName || !emailOk || customerPhoneDigits.length < 8) {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details:
            'Sunt necesare prenume, nume, email valid și telefon (minim 8 cifre).',
        },
        { status: 400 }
      );
    }

    if (customerFirstName.length > 80 || customerLastName.length > 80) {
      return NextResponse.json(
        {
          error: 'BAD_REQUEST',
          details: 'Prenumele și numele sunt prea lungi.',
        },
        { status: 400 }
      );
    }

    const customerFullName = `${customerFirstName} ${customerLastName}`.trim();

    // Generate invoice ONCE (reuse for all attempts)
    // Generate invoice as small integer (10 digits max) matching Reg.json style
    const invoice = Math.floor(Date.now() / 1000);

    // Insert into Supabase ONCE before trying any Paynet attempts
    // id (UUID) will be auto-generated by Supabase
    let data: { id: string };
    try {
      const result = await supabaseAdmin
        .from('orders')
        .insert({
          product_id: productId,
          amount: amount,
          currency: currency,
          status: 'pending',
          invoice: String(invoice),
          access_token: randomBytes(24).toString('base64url'),
          customer_name: customerFullName,
          customer_email: customerEmail,
          customer_phone: customerPhoneDigits,
        })
        .select()
        .single();

      if (result.error) {
        console.error('SUPABASE INSERT ERROR', result.error);
        const isFetchFailed =
          String(result.error.message || '').toLowerCase().includes('fetch failed') ||
          String(result.error.message || '').toLowerCase().includes('network');
        return NextResponse.json(
          {
            error: 'SUPABASE_INSERT_FAILED',
            details: result.error.message,
            code: result.error.code ?? null,
            hint: result.error.hint ?? (isFetchFailed
              ? 'Server could not reach Supabase. Check SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in env and that the server can reach the Supabase API.'
              : null),
          },
          { status: 500 }
        );
      }
      data = result.data as { id: string };
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e);
      const isFetchFailed = message.toLowerCase().includes('fetch failed') || message.toLowerCase().includes('network');
      console.error('SUPABASE INSERT THREW', e);
      return NextResponse.json(
        {
          error: 'SUPABASE_INSERT_FAILED',
          details: message,
          hint: isFetchFailed
            ? 'Server could not reach Supabase. Check SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in env and that the server can reach the Supabase API.'
            : null,
        },
        { status: 500 }
      );
    }

    const orderId = data.id; // Use the auto-generated UUID

    /** Paynet Customer / Payer: Name/email/phone from form; Code = unique id per order (not email). */
    const paynetCustomerBlock = {
      Code: orderId,
      Name: customerFullName,
      NameFirst: customerFirstName,
      NameLast: customerLastName,
      email: customerEmail,
      Country: 'Moldova',
      City: '-',
      Address: '-',
      PhoneNumber: customerPhoneDigits,
    };

    const apiHost = getApiHost();
    const portalHost = getPortalHost();
    const merchantCode = process.env.PAYNET_MERCHANT_CODE!;
    const saleAreaCode = process.env.PAYNET_SALE_AREA_CODE!;
    const callbackUrl = process.env.PAYNET_CALLBACK_URL!;

    // Authenticate with Paynet. Try with merchantcode+salearea first (Postman), then with username+password only (PHP SDK).
    const username = process.env.PAYNET_USERNAME!;
    const password = process.env.PAYNET_PASSWORD!;

    const tryAuth = async (params: Record<string, string>) => {
      const body = new URLSearchParams(params).toString();
      const res = await fetch(`${apiHost}/auth`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body,
      });
      const text = await res.text();
      return { ok: res.ok, status: res.status, text };
    };

    let authResponse = await tryAuth({
      grant_type: 'password',
      username,
      password,
      merchantcode: merchantCode,
      salearea: saleAreaCode,
    });

    if (!authResponse.ok && authResponse.text.toLowerCase().includes('invalid_grant')) {
      console.log('PAYNET AUTH: invalid_grant with merchantcode+salearea, retrying with username+password only (PHP SDK style)');
      authResponse = await tryAuth({
        grant_type: 'password',
        username,
        password,
      });
    }

    if (!authResponse.ok) {
      console.error('PAYNET AUTH STATUS', authResponse.status);
      console.error('PAYNET AUTH BODY', authResponse.text);
      const hint = authResponse.text.toLowerCase().includes('invalid_grant')
        ? ' Check PAYNET_USERNAME (User ID) and PAYNET_PASSWORD. No extra spaces. If you use PAYNET_SALE_AREA_CODE, confirm the value with Paynet.'
        : undefined;
      return NextResponse.json(
        {
          error: 'PAYNET_API_ERROR',
          step: 'auth',
          status: authResponse.status,
          details: authResponse.text,
          ...(hint && { hint }),
        },
        { status: 502 }
      );
    }

    let authData: { access_token?: string; token?: string };
    try {
      authData = JSON.parse(authResponse.text);
    } catch (e) {
      console.error('PAYNET AUTH PARSE ERROR', e);
      return NextResponse.json(
        {
          error: 'PAYNET_AUTH_FAILED',
          details: 'Failed to parse auth response',
        },
        { status: 502 }
      );
    }

    const accessToken = authData.access_token || authData.token;

    if (!accessToken) {
      console.error('No access token in auth response:', authData);
      return NextResponse.json(
        {
          error: 'PAYNET_AUTH_FAILED',
          details: 'No access_token in response',
        },
        { status: 502 }
      );
    }

    // Public URLs for success/cancel must match the canonical site host (e.g. www) — Paynet may reject
    // getecom if LinkUrl* differ from the merchant-registered domain. Prefer SITE_URL over callback host.
    const baseUrlFromCallback = callbackUrl.replace('/api/paynet/callback', '').replace(/\/$/, '');
    const baseUrl = (
      process.env.SITE_URL ||
      process.env.NEXT_PUBLIC_SITE_URL ||
      baseUrlFromCallback
    ).replace(/\/$/, '');

    // Define attempts: PHP SDK structure (NO Signature, SignVersion, MoneyType, WITH Lang) vs Reg.json structure (WITH them, NO Lang)
    // Also test JSON vs form-urlencoded
    const attempts = [
      // PHP SDK structure: NO Signature, SignVersion, MoneyType, WITH Lang, Payer=Customer object
      // JSON format
      { id: 'A', endpoint: 'Send', usePhpSdkStructure: true, useJson: true, amountValue: Math.round(amount * 100), includeSaleArea: false, description: 'PHP SDK structure (no Signature/SignVersion/MoneyType), JSON, minor units' },
      { id: 'B', endpoint: 'Send', usePhpSdkStructure: true, useJson: true, amountValue: Math.round(amount), includeSaleArea: false, description: 'PHP SDK structure (no Signature/SignVersion/MoneyType), JSON, major units' },
      
      // Reg.json structure: WITH Signature, SignVersion, MoneyType, NO Lang, Payer=null
      // JSON format
      { id: 'C', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount * 100), includeSaleArea: false, description: 'Reg.json structure (with Signature/SignVersion/MoneyType), JSON, minor units' },
      { id: 'D', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount), includeSaleArea: false, description: 'Reg.json structure (with Signature/SignVersion/MoneyType), JSON, major units' },

      // Reg.json structure WITH SaleAreaCode
      { id: 'E', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount * 100), includeSaleArea: true, description: 'Reg.json structure, WITH SaleAreaCode, minor units' },
      { id: 'F', endpoint: 'Send', usePhpSdkStructure: false, useJson: true, amountValue: Math.round(amount), includeSaleArea: true, description: 'Reg.json structure, WITH SaleAreaCode, major units' },
    ];

    const attemptResults: Array<{ attempt: string; status: number; body: string }> = [];

    // Try each attempt in order, stop on first success
    for (const attempt of attempts) {
      console.log('PAYNET_ATTEMPT', attempt.id);

      // Build payload INSIDE the loop for each attempt
      // Reuse invoice as small numeric (already generated above)
      const invoiceNumber = invoice; // Small number, ~10 digits

      // Build product matching Reg.json structure exactly
      const chosenAmount = attempt.amountValue;
      const product = {
        GroupName: null,
        QualitiesConcat: null,
        LineNo: 1,
        GroupId: null,
        Code: 'relatia360',
        Barcode: 3601,
        Name: 'RELAȚIA 360 – De la conflict la conectare',
        Description: 'Acces online',
        UnitPrice: chosenAmount, // int
        UnitProduct: null,
        Quantity: 100, // int - in minor units (100 = 1.00) per Reg.json example where 200 = 2.00
        Amount: null,
        Dimensions: null,
        Qualities: null,
        TotalAmount: chosenAmount, // int - should be UnitPrice * (Quantity/100) per PHP SDK calculation
      };

      // Build payload - PHP SDK structure vs Reg.json structure
      const basePayload: any = {
        Invoice: invoiceNumber, // NUMBER (small integer, ~10 digits)
        MerchantCode: merchantCode, // STRING "982657"
        LinkUrlSuccess: `${baseUrl}/multumim?order=${orderId}`,
        LinkUrlCancel: `${baseUrl}/plata?cancel=1&order=${orderId}`,
        Customer: { ...paynetCustomerBlock },
        Currency: 498, // int 498 for MDL
        ExternalDate: formatPaynetDate(new Date()), // today in Moldova timezone
        ExpiryDate: formatPaynetDate(new Date(Date.now() + 2 * 60 * 60 * 1000)), // +2 hours
        Services: [
          {
            Name: 'RELAȚIA 360',
            Description: 'Curs practic de comunicare în relații',
            Amount: chosenAmount, // Uppercase Amount (matching Reg.json)
            Products: [product], // Uppercase Products (matching Reg.json)
          },
        ],
      };

      // PHP SDK structure: NO Signature, SignVersion, MoneyType, WITH Lang, Payer=Customer
      // Reg.json structure: WITH Signature, SignVersion, MoneyType, NO Lang, Payer=null
      const regPayload: any = {
        ...basePayload,
        ...(attempt.usePhpSdkStructure ? {
          // PHP SDK structure
          Payer: { ...paynetCustomerBlock },
          Lang: 'ro', // PHP SDK includes Lang
          // NO Signature, SignVersion, MoneyType
        } : {
          // Reg.json structure
          Signature: null,
          SignVersion: 'v01', // Reg.json uses v01
          Payer: null, // Reg.json has Payer: null
          MoneyType: null,
          // NO Lang
        }),
        // Include SaleAreaCode only if attempt.includeSaleArea is true
        ...(attempt.includeSaleArea && { SaleAreaCode: saleAreaCode }),
      };

      // CRITICAL LOGGING: Log the exact payload that will be sent
      console.log('PAYNET_ATTEMPT', attempt.id);
      console.log('PAYNET_PAYLOAD_SENT', JSON.stringify(regPayload));

      // Determine endpoint path
      const endpointPath = attempt.endpoint ? `/api/Payments/${attempt.endpoint}` : '/api/Payments';

      // Determine Content-Type and body format
      // Note: PHP SDK uses form-urlencoded, but Postman uses JSON. Testing JSON first.
      const contentType = attempt.useJson ? 'application/json' : 'application/x-www-form-urlencoded';
      const requestBody = attempt.useJson 
        ? JSON.stringify(regPayload)
        : JSON.stringify(regPayload); // For now, keep JSON. Form-urlencoded would need nested structure flattening.

      // Try this attempt - use the payload built INSIDE this loop
      const paymentResponse = await fetch(`${apiHost}${endpointPath}`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': contentType,
        },
        body: requestBody,
      });

      const paymentResponseText = await paymentResponse.text();
      console.log('PAYNET_PAYMENTS_STATUS', paymentResponse.status);
      console.log('PAYNET_PAYMENTS_BODY', paymentResponseText);

      // Record attempt result
      attemptResults.push({
        attempt: attempt.id,
        status: paymentResponse.status,
        body: paymentResponseText,
      });

      // If successful, stop and return
      if (paymentResponse.ok) {
        let paymentData;
        try {
          paymentData = JSON.parse(paymentResponseText);
        } catch (e) {
          console.error('PAYNET PAYMENTS PARSE ERROR', e);
          // Continue to next attempt if parse fails
          continue;
        }

        // Paynet returns "PaymentId" (PascalCase); accept number or string
        const rawId = paymentData.PaymentId ?? paymentData.PaymentID ?? paymentData.paymentId ?? paymentData.id ?? paymentData.ID;
        const paymentId = rawId != null && rawId !== '' ? String(rawId) : null;
        const signature = paymentData.Signature || paymentData.signature;

        if (!paymentId) {
          console.error('No PaymentID in response:', paymentData);
          // Continue to next attempt
          continue;
        }

        // If Paynet returns a ready payment page URL, use it (avoids fragile getecom form binding).
        const directPaymentUrl =
          typeof paymentData.PaymentPageUrl === 'string' && paymentData.PaymentPageUrl.startsWith('http')
            ? paymentData.PaymentPageUrl
            : typeof paymentData.PaymentUrl === 'string' && paymentData.PaymentUrl.startsWith('http')
              ? paymentData.PaymentUrl
              : typeof paymentData.RedirectUrl === 'string' && paymentData.RedirectUrl.startsWith('http')
                ? paymentData.RedirectUrl
                : typeof paymentData.Url === 'string' && paymentData.Url.startsWith('http')
                  ? paymentData.Url
                  : null;

        // Update order with paynet_payment_id and signature
        const updateData: any = {
          paynet_payment_id: Number(paymentId),
        };

        if (signature) {
          updateData.paynet_signature = signature;
        }

        const { error: updateError } = await supabaseAdmin
          .from('orders')
          .update(updateData)
          .eq('id', orderId);

        if (updateError) {
          console.error('Failed to update order with payment ID:', updateError);
          // Continue anyway, payment was created
        }

        const successUrl = `${baseUrl}/multumim?order=${orderId}`;
        const cancelUrl = `${baseUrl}/plata?cancel=1&order=${orderId}`;
        const expiryDate = formatPaynetDate(new Date(Date.now() + 2 * 60 * 60 * 1000));

        if (directPaymentUrl) {
          return NextResponse.json({
            ok: true,
            orderId: orderId,
            invoice: String(invoice),
            payment_id: paymentId.toString(),
            signature: signature || null,
            attempt: attempt.id,
            payment_url: directPaymentUrl,
          });
        }

        // Paynet getecom: use Operation (PascalCase); lowercase "operation" often fails ASP.NET model binding → CustomException.
        const redirectAction = `${portalHost}/acquiring/getecom`;
        const paynet_redirect_params: Record<string, string> = {
          Operation: paymentId.toString(),
          LinkUrlSuccess: successUrl,
          LinkUrlCancel: cancelUrl,
          ExpiryDate: expiryDate,
          Lang: 'ro',
        };
        if (signature) paynet_redirect_params.Signature = signature;

        return NextResponse.json({
          ok: true,
          orderId: orderId,
          invoice: String(invoice),
          payment_id: paymentId.toString(),
          signature: signature || null,
          attempt: attempt.id,
          paynet_redirect_action: redirectAction,
          paynet_redirect_params,
        });
      }

      // If not successful, continue to next attempt
      console.log(`PAYNET_ATTEMPT ${attempt.id} failed, trying next...`);
    }

    // All attempts failed
    return NextResponse.json(
      {
        error: 'PAYNET_PAYMENTS_FAILED',
        attempts: attemptResults,
        note: 'All attempts failed. Check PAYNET_ATTEMPT logs in Vercel.',
      },
      { status: 502 }
    );
  } catch (e) {
    console.error('PAYNET CREATE FATAL', e);
    return NextResponse.json(
      {
        error: 'Internal server error',
        details: String((e as any)?.message ?? e),
      },
      { status: 500 }
    );
  }
}

